edition = "2021"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
max_width = 80
reorder_imports = true
reorder_impl_items = true
wrap_comments = true
format_strings = true
format_code_in_doc_comments = true
