[package]
name = "fhtml"
edition = "2021"
version.workspace = true

[features]
const_format = ["dep:const_format"]

[dependencies]
const_format = { version = "0.2", optional = true }
fhtml-macros.path = "../fhtml-macros"
